name: Deploy to huggingface

on:
  push:
    branches: [main]

  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: git push --force https://Jacmon:$HF_TOKEN@huggingface.co/spaces/Jacmon/Portfolio-rebalancer main